### ISSUE TITLE
How to see what triggered pdirty()

### ISSUE THREAD

**Issue by turner-noad** [onyx-and-iris/voicemeeter-api-python#14]
Hello!

I've already set up an observer for the `on_pdirty()` event, with it triggering exactly as expected:
```
def on_pdirty(self):
    print("Triggered")
```
However, how can I see what exactly changed to trigger this event, similar to `vm.midi.current` but for pdirty?

Many thanks in advance!

**Comment by onyx-and-iris** [comment]
Hey, due to the design of the API, `VBVMR_IsParametersDirty` can only notify that something has changed but it gives no indication as to what has changed. You'll have to track parameter values yourself and update them on each pdirty event. You can find an example of this pattern in the [API repository](https://github.com/vburel2018/Voicemeeter-SDK/blob/main/example0/vmr_client.c#L1771). There have been lots of discussions on this topic in the Discord `vm-remote-api` channel feel free to check some of the past posts there if you'd like further insight.

I hope that's helpful.
